package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAdvertiseCatalog generated by hbm2java
 */
@Entity
@Table(name = "tb_advertise_catalog")
public class TbAdvertiseCatalog implements java.io.Serializable {

	private Long tacId;
	private String tacName;
	private String tacDesp;
	private Date tacAddDate;
	private Long tacAddPerson;
	private Integer tacStatus;

	public TbAdvertiseCatalog() {
	}

	public TbAdvertiseCatalog(String tacName, Date tacAddDate, Integer tacStatus) {
		this.tacName = tacName;
		this.tacAddDate = tacAddDate;
		this.tacStatus = tacStatus;
	}

	public TbAdvertiseCatalog(String tacName, String tacDesp, Date tacAddDate, Long tacAddPerson, Integer tacStatus) {
		this.tacName = tacName;
		this.tacDesp = tacDesp;
		this.tacAddDate = tacAddDate;
		this.tacAddPerson = tacAddPerson;
		this.tacStatus = tacStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tac_id", unique = true, nullable = false)
	public Long getTacId() {
		return this.tacId;
	}

	public void setTacId(Long tacId) {
		this.tacId = tacId;
	}

	@Column(name = "tac_name", nullable = false, length = 20)
	public String getTacName() {
		return this.tacName;
	}

	public void setTacName(String tacName) {
		this.tacName = tacName;
	}

	@Column(name = "tac_desp", length = 256)
	public String getTacDesp() {
		return this.tacDesp;
	}

	public void setTacDesp(String tacDesp) {
		this.tacDesp = tacDesp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tac_add_date", nullable = false, length = 19)
	public Date getTacAddDate() {
		return this.tacAddDate;
	}

	public void setTacAddDate(Date tacAddDate) {
		this.tacAddDate = tacAddDate;
	}

	@Column(name = "tac_add_person")
	public Long getTacAddPerson() {
		return this.tacAddPerson;
	}

	public void setTacAddPerson(Long tacAddPerson) {
		this.tacAddPerson = tacAddPerson;
	}

	@Column(name = "tac_status", nullable = false)
	public Integer getTacStatus() {
		return this.tacStatus;
	}

	public void setTacStatus(Integer tacStatus) {
		this.tacStatus = tacStatus;
	}

}
