package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbAdvertiseContent generated by hbm2java
 */
@Entity
@Table(name = "tb_advertise_content")
public class TbAdvertiseContent implements java.io.Serializable {

	private Long tacId;
	private Long tacCataId;
	private String tacName;
	private String tacPhoneImage;
	private String tacWebImage;
	private String tacLink;
	private Date tacAddDate;
	private Long tacAddPerson;
	private Integer tacStatus;

	public TbAdvertiseContent() {
	}

	public TbAdvertiseContent(Long tacCataId, Date tacAddDate, Integer tacStatus) {
		this.tacCataId = tacCataId;
		this.tacAddDate = tacAddDate;
		this.tacStatus = tacStatus;
	}

	public TbAdvertiseContent(Long tacCataId, String tacName, String tacPhoneImage, String tacWebImage, String tacLink,
			Date tacAddDate, Long tacAddPerson, Integer tacStatus) {
		this.tacCataId = tacCataId;
		this.tacName = tacName;
		this.tacPhoneImage = tacPhoneImage;
		this.tacWebImage = tacWebImage;
		this.tacLink = tacLink;
		this.tacAddDate = tacAddDate;
		this.tacAddPerson = tacAddPerson;
		this.tacStatus = tacStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tac_id", unique = true, nullable = false)
	public Long getTacId() {
		return this.tacId;
	}

	public void setTacId(Long tacId) {
		this.tacId = tacId;
	}

	@Column(name = "tac_cata_id", nullable = false)
	public Long getTacCataId() {
		return this.tacCataId;
	}

	public void setTacCataId(Long tacCataId) {
		this.tacCataId = tacCataId;
	}

	@Column(name = "tac_name", length = 256)
	public String getTacName() {
		return this.tacName;
	}

	public void setTacName(String tacName) {
		this.tacName = tacName;
	}

	@Column(name = "tac_phone_image", length = 256)
	public String getTacPhoneImage() {
		return this.tacPhoneImage;
	}

	public void setTacPhoneImage(String tacPhoneImage) {
		this.tacPhoneImage = tacPhoneImage;
	}

	@Column(name = "tac_web_image", length = 256)
	public String getTacWebImage() {
		return this.tacWebImage;
	}

	public void setTacWebImage(String tacWebImage) {
		this.tacWebImage = tacWebImage;
	}

	@Column(name = "tac_link", length = 256)
	public String getTacLink() {
		return this.tacLink;
	}

	public void setTacLink(String tacLink) {
		this.tacLink = tacLink;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tac_add_date", nullable = false, length = 19)
	public Date getTacAddDate() {
		return this.tacAddDate;
	}

	public void setTacAddDate(Date tacAddDate) {
		this.tacAddDate = tacAddDate;
	}

	@Column(name = "tac_add_person")
	public Long getTacAddPerson() {
		return this.tacAddPerson;
	}

	public void setTacAddPerson(Long tacAddPerson) {
		this.tacAddPerson = tacAddPerson;
	}

	@Column(name = "tac_status", nullable = false)
	public Integer getTacStatus() {
		return this.tacStatus;
	}

	public void setTacStatus(Integer tacStatus) {
		this.tacStatus = tacStatus;
	}

}
