package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbCustMachine generated by hbm2java
 */
@Entity
@Table(name = "tb_cust_machine")
public class TbCustMachine implements java.io.Serializable {

	private Long tcmId;
	private Long tcmCustomerId;
	private Long tcmType;
	private String tcmCode;
	private Long tcmBrand;
	private Long tcmModel;
	private String tcmUse;
	private String tcmDesp;
	private Date tcmAddDate;
	private Integer tcmStatus;

	public TbCustMachine() {
	}

	public TbCustMachine(Long tcmCustomerId, Long tcmType, String tcmCode, Long tcmBrand, Long tcmModel,
			Date tcmAddDate, Integer tcmStatus) {
		this.tcmCustomerId = tcmCustomerId;
		this.tcmType = tcmType;
		this.tcmCode = tcmCode;
		this.tcmBrand = tcmBrand;
		this.tcmModel = tcmModel;
		this.tcmAddDate = tcmAddDate;
		this.tcmStatus = tcmStatus;
	}

	public TbCustMachine(Long tcmCustomerId, Long tcmType, String tcmCode, Long tcmBrand, Long tcmModel, String tcmUse,
			String tcmDesp, Date tcmAddDate, Integer tcmStatus) {
		this.tcmCustomerId = tcmCustomerId;
		this.tcmType = tcmType;
		this.tcmCode = tcmCode;
		this.tcmBrand = tcmBrand;
		this.tcmModel = tcmModel;
		this.tcmUse = tcmUse;
		this.tcmDesp = tcmDesp;
		this.tcmAddDate = tcmAddDate;
		this.tcmStatus = tcmStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tcm_id", unique = true, nullable = false)
	public Long getTcmId() {
		return this.tcmId;
	}

	public void setTcmId(Long tcmId) {
		this.tcmId = tcmId;
	}

	@Column(name = "tcm_customer_id", nullable = false)
	public Long getTcmCustomerId() {
		return this.tcmCustomerId;
	}

	public void setTcmCustomerId(Long tcmCustomerId) {
		this.tcmCustomerId = tcmCustomerId;
	}

	@Column(name = "tcm_type", nullable = false)
	public Long getTcmType() {
		return this.tcmType;
	}

	public void setTcmType(Long tcmType) {
		this.tcmType = tcmType;
	}

	@Column(name = "tcm_code", nullable = false, length = 50)
	public String getTcmCode() {
		return this.tcmCode;
	}

	public void setTcmCode(String tcmCode) {
		this.tcmCode = tcmCode;
	}

	@Column(name = "tcm_brand", nullable = false)
	public Long getTcmBrand() {
		return this.tcmBrand;
	}

	public void setTcmBrand(Long tcmBrand) {
		this.tcmBrand = tcmBrand;
	}

	@Column(name = "tcm_model", nullable = false)
	public Long getTcmModel() {
		return this.tcmModel;
	}

	public void setTcmModel(Long tcmModel) {
		this.tcmModel = tcmModel;
	}

	@Column(name = "tcm_use", length = 200)
	public String getTcmUse() {
		return this.tcmUse;
	}

	public void setTcmUse(String tcmUse) {
		this.tcmUse = tcmUse;
	}

	@Column(name = "tcm_desp", length = 500)
	public String getTcmDesp() {
		return this.tcmDesp;
	}

	public void setTcmDesp(String tcmDesp) {
		this.tcmDesp = tcmDesp;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tcm_add_date", nullable = false, length = 19)
	public Date getTcmAddDate() {
		return this.tcmAddDate;
	}

	public void setTcmAddDate(Date tcmAddDate) {
		this.tcmAddDate = tcmAddDate;
	}

	@Column(name = "tcm_status", nullable = false)
	public Integer getTcmStatus() {
		return this.tcmStatus;
	}

	public void setTcmStatus(Integer tcmStatus) {
		this.tcmStatus = tcmStatus;
	}

}
