package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbCustomers generated by hbm2java
 */
@Entity
@Table(name = "tb_customers")
public class TbCustomers implements java.io.Serializable {

	private Long tcId;
	private String tcName;
	private String tcSimpleName;
	private Long tcType;
	private Integer tcProvId;
	private String pname;
	private Integer tcCityId;
	private String cname;
	private String tcAddress;
	private String tcPerson;
	private String tcMobile;
	private Timestamp tcAddDate;
	private Long tcAddPerson;
	private String tcLoginUser;
	private String tcLoginPass;
	private Integer tcStatus;
	private Long tcServicePoint;
	private String tcPhoto;
	private String tcNumber;
	private Integer tcRegionId;
	private String tcDeviceinfo;
	private Double tcLatitude;
	private Double tcLongtude;
	private String twType;
	private String tspName;
	private Long tcCompanyId;
	private Integer tcLevel;

	public TbCustomers() {
	}

	public TbCustomers(String tcName, String tcSimpleName, Long tcType, Timestamp tcAddDate, Long tcAddPerson,
			String tcLoginUser, String tcLoginPass, String tcNumber) {
		this.tcName = tcName;
		this.tcSimpleName = tcSimpleName;
		this.tcType = tcType;
		this.tcAddDate = tcAddDate;
		this.tcAddPerson = tcAddPerson;
		this.tcLoginUser = tcLoginUser;
		this.tcLoginPass = tcLoginPass;
		this.tcNumber = tcNumber;
	}

	public TbCustomers(Long tcId, Long tcCompanyId, String tcName,
			String tcSimpleName, Long tcType, Integer tcProvId, String pname,
			Integer tcCityId, String cname, String tcAddress, String tcPerson,
			String tcMobile, Timestamp tcAddDate, Long tcAddPerson,
			String tcLoginUser, String tcLoginPass, Integer tcStatus,
			Long tcServicePoint, String tcPhoto, String tcNumber,
			Integer tcRegionId, String tcDeviceinfo, Double tcLatitude,
			Double tcLongtude, String twType, String tspName) {
		super();
		this.tcId = tcId;
		this.tcCompanyId = tcCompanyId;
		this.tcName = tcName;
		this.tcSimpleName = tcSimpleName;
		this.tcType = tcType;
		this.tcProvId = tcProvId;
		this.pname = pname;
		this.tcCityId = tcCityId;
		this.cname = cname;
		this.tcAddress = tcAddress;
		this.tcPerson = tcPerson;
		this.tcMobile = tcMobile;
		this.tcAddDate = tcAddDate;
		this.tcAddPerson = tcAddPerson;
		this.tcLoginUser = tcLoginUser;
		this.tcLoginPass = tcLoginPass;
		this.tcStatus = tcStatus;
		this.tcServicePoint = tcServicePoint;
		this.tcPhoto = tcPhoto;
		this.tcNumber = tcNumber;
		this.tcRegionId = tcRegionId;
		this.tcDeviceinfo = tcDeviceinfo;
		this.tcLatitude = tcLatitude;
		this.tcLongtude = tcLongtude;
		this.twType = twType;
		this.tspName = tspName;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tc_id", unique = true, nullable = false)
	public Long getTcId() {
		return this.tcId;
	}

	public void setTcId(Long tcId) {
		this.tcId = tcId;
	}

	@Column(name = "tc_name", nullable = false, length = 50)
	public String getTcName() {
		return this.tcName;
	}

	public void setTcName(String tcName) {
		this.tcName = tcName;
	}

	@Column(name = "tc_simple_name", nullable = false, length = 10)
	public String getTcSimpleName() {
		return this.tcSimpleName;
	}

	public void setTcSimpleName(String tcSimpleName) {
		this.tcSimpleName = tcSimpleName;
	}

	@Column(name = "tc_type", nullable = false)
	public Long getTcType() {
		return this.tcType;
	}

	public void setTcType(Long tcType) {
		this.tcType = tcType;
	}

	@Column(name = "tc_prov_id")
	public Integer getTcProvId() {
		return this.tcProvId;
	}

	public void setTcProvId(Integer tcProvId) {
		this.tcProvId = tcProvId;
	}

	@Column(name = "tc_city_id")
	public Integer getTcCityId() {
		return this.tcCityId;
	}

	public void setTcCityId(Integer tcCityId) {
		this.tcCityId = tcCityId;
	}

	@Column(name = "tc_address", length = 50)
	public String getTcAddress() {
		return this.tcAddress;
	}

	public void setTcAddress(String tcAddress) {
		this.tcAddress = tcAddress;
	}

	@Column(name = "tc_person", length = 10)
	public String getTcPerson() {
		return this.tcPerson;
	}

	public void setTcPerson(String tcPerson) {
		this.tcPerson = tcPerson;
	}

	@Column(name = "tc_mobile", length = 21)
	public String getTcMobile() {
		return this.tcMobile;
	}

	public void setTcMobile(String tcMobile) {
		this.tcMobile = tcMobile;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tc_add_date", nullable = false, length = 19)
	public Timestamp getTcAddDate() {
		return this.tcAddDate;
	}

	public void setTcAddDate(Timestamp tcAddDate) {
		this.tcAddDate = tcAddDate;
	}

	@Column(name = "tc_add_person", nullable = false)
	public Long getTcAddPerson() {
		return this.tcAddPerson;
	}

	public void setTcAddPerson(Long tcAddPerson) {
		this.tcAddPerson = tcAddPerson;
	}

	@Column(name = "tc_login_user", nullable = false, length = 20)
	public String getTcLoginUser() {
		return this.tcLoginUser;
	}

	public void setTcLoginUser(String tcLoginUser) {
		this.tcLoginUser = tcLoginUser;
	}

	@Column(name = "tc_login_pass", nullable = false, length = 50)
	public String getTcLoginPass() {
		return this.tcLoginPass;
	}

	public void setTcLoginPass(String tcLoginPass) {
		this.tcLoginPass = tcLoginPass;
	}

	@Column(name = "tc_status")
	public Integer getTcStatus() {
		return this.tcStatus;
	}

	public void setTcStatus(Integer tcStatus) {
		this.tcStatus = tcStatus;
	}

	@Column(name = "tc_service_point")
	public Long getTcServicePoint() {
		return this.tcServicePoint;
	}

	public void setTcServicePoint(Long tcServicePoint) {
		this.tcServicePoint = tcServicePoint;
	}

	@Column(name = "tc_photo", length = 225)
	public String getTcPhoto() {
		return this.tcPhoto;
	}

	public void setTcPhoto(String tcPhoto) {
		this.tcPhoto = tcPhoto;
	}

	@Column(name = "tc_number", nullable = false, length = 50)
	public String getTcNumber() {
		return this.tcNumber;
	}

	public void setTcNumber(String tcNumber) {
		this.tcNumber = tcNumber;
	}

	@Column(name = "tc_region_id")
	public Integer getTcRegionId() {
		return this.tcRegionId;
	}

	public void setTcRegionId(Integer tcRegionId) {
		this.tcRegionId = tcRegionId;
	}

	@Column(name = "tc_deviceinfo", length = 225)
	public String getTcDeviceinfo() {
		return this.tcDeviceinfo;
	}

	public void setTcDeviceinfo(String tcDeviceinfo) {
		this.tcDeviceinfo = tcDeviceinfo;
	}

	@Column(name = "tc_latitude")
	public Double getTcLatitude() {
		return this.tcLatitude;
	}

	public void setTcLatitude(Double tcLatitude) {
		this.tcLatitude = tcLatitude;
	}

	@Column(name = "tc_longtude")
	public Double getTcLongtude() {
		return this.tcLongtude;
	}

	public void setTcLongtude(Double tcLongtude) {
		this.tcLongtude = tcLongtude;
	}

	
	
	@Column(name = "tc_company_id")
	public Long getTcCompanyId() {
		return tcCompanyId;
	}

	public void setTcCompanyId(Long tcCompanyId) {
		this.tcCompanyId = tcCompanyId;
	}

	
	@Column(name = "tc_level")
	public Integer getTcLevel() {
		return tcLevel;
	}

	public void setTcLevel(Integer tcLevel) {
		this.tcLevel = tcLevel;
	}

	@Transient
	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Transient
	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Transient
	public String getTwType() {
		return twType;
	}

	public void setTwType(String twType) {
		this.twType = twType;
	}

	@Transient
	public String getTspName() {
		return tspName;
	}

	public void setTspName(String tspName) {
		this.tspName = tspName;
	}

}
