package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbEmployeePosition generated by hbm2java
 */
@Entity
@Table(name = "tb_employee_position")
public class TbEmployeePosition implements java.io.Serializable {

	private Long tepId;
	private Long tepEmployeeId;
	private Double tepLatitude;
	private Double tepLongtude;
	private Date tepAddDate;
	private Integer tepStatus;

	public TbEmployeePosition() {
	}

	public TbEmployeePosition(Long tepEmployeeId, Double tepLatitude, Double tepLongtude, Date tepAddDate) {
		this.tepEmployeeId = tepEmployeeId;
		this.tepLatitude = tepLatitude;
		this.tepLongtude = tepLongtude;
		this.tepAddDate = tepAddDate;
	}

	public TbEmployeePosition(Long tepEmployeeId, Double tepLatitude, Double tepLongtude, Date tepAddDate,
			Integer tepStatus) {
		this.tepEmployeeId = tepEmployeeId;
		this.tepLatitude = tepLatitude;
		this.tepLongtude = tepLongtude;
		this.tepAddDate = tepAddDate;
		this.tepStatus = tepStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tep_id", unique = true, nullable = false)
	public Long getTepId() {
		return this.tepId;
	}

	public void setTepId(Long tepId) {
		this.tepId = tepId;
	}

	@Column(name = "tep_employee_id", nullable = false)
	public Long getTepEmployeeId() {
		return this.tepEmployeeId;
	}

	public void setTepEmployeeId(Long tepEmployeeId) {
		this.tepEmployeeId = tepEmployeeId;
	}

	@Column(name = "tep_latitude", nullable = false, precision = 22, scale = 0)
	public Double getTepLatitude() {
		return this.tepLatitude;
	}

	public void setTepLatitude(Double tepLatitude) {
		this.tepLatitude = tepLatitude;
	}

	@Column(name = "tep_longtude", nullable = false, precision = 22, scale = 0)
	public Double getTepLongtude() {
		return this.tepLongtude;
	}

	public void setTepLongtude(Double tepLongtude) {
		this.tepLongtude = tepLongtude;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tep_add_date", nullable = false, length = 19)
	public Date getTepAddDate() {
		return this.tepAddDate;
	}

	public void setTepAddDate(Date tepAddDate) {
		this.tepAddDate = tepAddDate;
	}

	@Column(name = "tep_status")
	public Integer getTepStatus() {
		return this.tepStatus;
	}

	public void setTepStatus(Integer tepStatus) {
		this.tepStatus = tepStatus;
	}

}
