package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbInformationCata generated by hbm2java
 */
@Entity
@Table(name = "tb_information_cata")
public class TbInformationCata implements java.io.Serializable {

	private Long ticId;
	private String ticName;
	private Long ticParentId;
	private Integer ticOrder;
	private Date ticAddDate;
	private Integer ticStatus;
	private Set<TbInformation> tbInformations = new HashSet<TbInformation>(0);

	public TbInformationCata() {
	}

	public TbInformationCata(String ticName, Long ticParentId, Date ticAddDate, Integer ticStatus) {
		this.ticName = ticName;
		this.ticParentId = ticParentId;
		this.ticAddDate = ticAddDate;
		this.ticStatus = ticStatus;
	}

	public TbInformationCata(String ticName, Long ticParentId, Integer ticOrder, Date ticAddDate, Integer ticStatus,
			Set<TbInformation> tbInformations) {
		this.ticName = ticName;
		this.ticParentId = ticParentId;
		this.ticOrder = ticOrder;
		this.ticAddDate = ticAddDate;
		this.ticStatus = ticStatus;
		this.tbInformations = tbInformations;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tic_id", unique = true, nullable = false)
	public Long getTicId() {
		return this.ticId;
	}

	public void setTicId(Long ticId) {
		this.ticId = ticId;
	}

	@Column(name = "tic_name", nullable = false, length = 20)
	public String getTicName() {
		return this.ticName;
	}

	public void setTicName(String ticName) {
		this.ticName = ticName;
	}

	@Column(name = "tic_parent_id", nullable = false)
	public Long getTicParentId() {
		return this.ticParentId;
	}

	public void setTicParentId(Long ticParentId) {
		this.ticParentId = ticParentId;
	}

	@Column(name = "tic_order")
	public Integer getTicOrder() {
		return this.ticOrder;
	}

	public void setTicOrder(Integer ticOrder) {
		this.ticOrder = ticOrder;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tic_add_date", nullable = false, length = 19)
	public Date getTicAddDate() {
		return this.ticAddDate;
	}

	public void setTicAddDate(Date ticAddDate) {
		this.ticAddDate = ticAddDate;
	}

	@Column(name = "tic_status", nullable = false)
	public Integer getTicStatus() {
		return this.ticStatus;
	}

	public void setTicStatus(Integer ticStatus) {
		this.ticStatus = ticStatus;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tbInformationCata")
	public Set<TbInformation> getTbInformations() {
		return this.tbInformations;
	}

	public void setTbInformations(Set<TbInformation> tbInformations) {
		this.tbInformations = tbInformations;
	}

}
