package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbInformation generated by hbm2java
 */
@Entity
@Table(name = "tb_information")
public class TbInformation implements java.io.Serializable {

	private Long tiId;
	private TbInformationCata tbInformationCata;
	private String tiTitle;
	private String tiContent;
	private Date tiAddDate;
	private Integer tiStatus;
	private Long tiPartion;

	public TbInformation() {
	}

	public TbInformation(TbInformationCata tbInformationCata, String tiTitle, String tiContent, Date tiAddDate,
			Integer tiStatus) {
		this.tbInformationCata = tbInformationCata;
		this.tiTitle = tiTitle;
		this.tiContent = tiContent;
		this.tiAddDate = tiAddDate;
		this.tiStatus = tiStatus;
	}

	public TbInformation(TbInformationCata tbInformationCata, String tiTitle, String tiContent, Date tiAddDate,
			Integer tiStatus, Long tiPartion) {
		this.tbInformationCata = tbInformationCata;
		this.tiTitle = tiTitle;
		this.tiContent = tiContent;
		this.tiAddDate = tiAddDate;
		this.tiStatus = tiStatus;
		this.tiPartion = tiPartion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ti_id", unique = true, nullable = false)
	public Long getTiId() {
		return this.tiId;
	}

	public void setTiId(Long tiId) {
		this.tiId = tiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ti_cata_id", nullable = false)
	public TbInformationCata getTbInformationCata() {
		return this.tbInformationCata;
	}

	public void setTbInformationCata(TbInformationCata tbInformationCata) {
		this.tbInformationCata = tbInformationCata;
	}

	@Column(name = "ti_title", nullable = false, length = 50)
	public String getTiTitle() {
		return this.tiTitle;
	}

	public void setTiTitle(String tiTitle) {
		this.tiTitle = tiTitle;
	}

	@Column(name = "ti_content", nullable = false, length = 65535)
	public String getTiContent() {
		return this.tiContent;
	}

	public void setTiContent(String tiContent) {
		this.tiContent = tiContent;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "ti_add_date", nullable = false, length = 19)
	public Date getTiAddDate() {
		return this.tiAddDate;
	}

	public void setTiAddDate(Date tiAddDate) {
		this.tiAddDate = tiAddDate;
	}

	@Column(name = "ti_status", nullable = false)
	public Integer getTiStatus() {
		return this.tiStatus;
	}

	public void setTiStatus(Integer tiStatus) {
		this.tiStatus = tiStatus;
	}

	@Column(name = "ti_partion")
	public Long getTiPartion() {
		return this.tiPartion;
	}

	public void setTiPartion(Long tiPartion) {
		this.tiPartion = tiPartion;
	}

}
