package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import com.fasterxml.jackson.annotation.JsonFormat;

import javax.persistence.*;
import java.sql.Timestamp;

import static javax.persistence.GenerationType.IDENTITY;

/**
 * TbItem generated by hbm2java
 */
@Entity
@Table(name = "tb_item", catalog = "mservice_hjtech")
public class TbItem implements java.io.Serializable {

	private Long tiId;
	private Long tiUplevelId;
	private String tiUplevelName;
	private String tiName;
	private String tiDesp;
	private Timestamp tiAdddate;
	private Long tiAddperson;
	private Integer tiStatus;
	private Long tiCategoryId;//商品类型id（关联tb_category表）
	private Integer itemOrderCount;
	private Long tiCompanyId;
	
	public TbItem() {
	}

	public TbItem(Long tiUplevelId, String tiName, Integer tiStatus) {
		this.tiUplevelId = tiUplevelId;
		this.tiName = tiName;
		this.tiStatus = tiStatus;
	}

	public TbItem(Long tiId, Long tiUplevelId, String tiUplevelName,
                  String tiName, String tiDesp, Timestamp tiAdddate,
                  Long tiAddperson, Integer tiStatus, Long tiCategoryId) {
		super();
		this.tiId = tiId;
		this.tiUplevelId = tiUplevelId;
		this.tiUplevelName = tiUplevelName;
		this.tiName = tiName;
		this.tiDesp = tiDesp;
		this.tiAdddate = tiAdddate;
		this.tiAddperson = tiAddperson;
		this.tiStatus = tiStatus;
		this.tiCategoryId = tiCategoryId;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ti_id", unique = true, nullable = false)
	public Long getTiId() {
		return this.tiId;
	}

	public void setTiId(Long tiId) {
		this.tiId = tiId;
	}

	@Column(name = "ti_uplevel_id", nullable = false)
	public Long getTiUplevelId() {
		return this.tiUplevelId;
	}

	public void setTiUplevelId(Long tiUplevelId) {
		this.tiUplevelId = tiUplevelId;
	}

	@Column(name = "ti_name", nullable = false, length = 10)
	public String getTiName() {
		return this.tiName;
	}

	public void setTiName(String tiName) {
		this.tiName = tiName;
	}

	@Column(name = "ti_desp", length = 200)
	public String getTiDesp() {
		return this.tiDesp;
	}

	public void setTiDesp(String tiDesp) {
		this.tiDesp = tiDesp;
	}

	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+08:00")
	@Column(name = "ti_adddate", length = 19)
	public Timestamp getTiAdddate() {
		return this.tiAdddate;
	}

	public void setTiAdddate(Timestamp tiAdddate) {
		this.tiAdddate = tiAdddate;
	}

	@Column(name = "ti_addperson")
	public Long getTiAddperson() {
		return this.tiAddperson;
	}

	public void setTiAddperson(Long tiAddperson) {
		this.tiAddperson = tiAddperson;
	}

	@Column(name = "ti_status", nullable = false)
	public Integer getTiStatus() {
		return this.tiStatus;
	}

	public void setTiStatus(Integer tiStatus) {
		this.tiStatus = tiStatus;
	}
	@Column(name = "ti_category_id", nullable = false)
	public Long getTiCategoryId() {
		return tiCategoryId;
	}

	public void setTiCategoryId(Long tiCategoryId) {
		this.tiCategoryId = tiCategoryId;
	}
	@Column(name = "ti_company_id")
	public Long getTiCompanyId() {
		return tiCompanyId;
	}

	public void setTiCompanyId(Long tiCompanyId) {
		this.tiCompanyId = tiCompanyId;
	}

	@Transient
	public String getTiUplevelName() {
		return tiUplevelName;
	}

	public void setTiUplevelName(String tiUplevelName) {
		this.tiUplevelName = tiUplevelName;
	}
	@Transient
	public Integer getItemOrderCount() {
		return itemOrderCount;
	}

	public void setItemOrderCount(Integer itemOrderCount) {
		this.itemOrderCount = itemOrderCount;
	}
}
