package com.src.api.entity;
// Generated 2015-9-7 15:54:27 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbMachineDetails generated by hbm2java
 */
@Entity
@Table(name = "tb_machine_details")
public class TbMachineDetails implements java.io.Serializable {

	private Long tmdId;
	private Long tmdMachineId;
	private Timestamp tmdDate;
	private Double tmdSellingPrice;
	private Double tmdLeasePrice;
	private Double tmdMonthLeasePrice;
	private Long tmdLeaseTime;
	private String tmdMachineThumbnail;
	private String tmdMachinePhoto;
	private String tmdBrief;

	public TbMachineDetails() {
	}


	public TbMachineDetails(Long tmdMachineId, Timestamp tmdDate, Double tmdSellingPrice, Double tmdLeasePrice,
			Double tmdMonthLeasePrice, Long tmdLeaseTime, String tmdMachineThumbnail, String tmdMachinePhoto,
			String tmdBrief) {
		this.tmdMachineId = tmdMachineId;
		this.tmdDate = tmdDate;
		this.tmdSellingPrice = tmdSellingPrice;
		this.tmdLeasePrice = tmdLeasePrice;
		this.tmdMonthLeasePrice = tmdMonthLeasePrice;
		this.tmdLeaseTime = tmdLeaseTime;
		this.tmdMachineThumbnail = tmdMachineThumbnail;
		this.tmdMachinePhoto = tmdMachinePhoto;
		this.tmdBrief = tmdBrief;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tmd_id", unique = true, nullable = false)
	public Long getTmdId() {
		return this.tmdId;
	}

	public void setTmdId(Long tmdId) {
		this.tmdId = tmdId;
	}

	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone = "GMT+08:00")
	@Column(name = "tmd_date", length = 19)
	public Timestamp getTmdDate() {
		return this.tmdDate;
	}

	public void setTmdDate(Timestamp tmdDate) {
		this.tmdDate = tmdDate;
	}

	@Column(name = "tmd_selling_price", precision = 8)
	public Double getTmdSellingPrice() {
		return this.tmdSellingPrice;
	}

	public void setTmdSellingPrice(Double tmdSellingPrice) {
		this.tmdSellingPrice = tmdSellingPrice;
	}

	@Column(name = "tmd_lease_price", precision = 8)
	public Double getTmdLeasePrice() {
		return this.tmdLeasePrice;
	}

	public void setTmdLeasePrice(Double tmdLeasePrice) {
		this.tmdLeasePrice = tmdLeasePrice;
	}

	@Column(name = "tmd_month_lease_price", precision = 8)
	public Double getTmdMonthLeasePrice() {
		return this.tmdMonthLeasePrice;
	}

	public void setTmdMonthLeasePrice(Double tmdMonthLeasePrice) {
		this.tmdMonthLeasePrice = tmdMonthLeasePrice;
	}

	@Column(name = "tmd_lease_time")
	public Long getTmdLeaseTime() {
		return this.tmdLeaseTime;
	}

	public void setTmdLeaseTime(Long tmdLeaseTime) {
		this.tmdLeaseTime = tmdLeaseTime;
	}

	@Column(name = "tmd_machine_thumbnail", length = 256)
	public String getTmdMachineThumbnail() {
		return this.tmdMachineThumbnail;
	}

	public void setTmdMachineThumbnail(String tmdMachineThumbnail) {
		this.tmdMachineThumbnail = tmdMachineThumbnail;
	}

	@Column(name = "tmd_machine_photo", length = 500)
	public String getTmdMachinePhoto() {
		return this.tmdMachinePhoto;
	}

	public void setTmdMachinePhoto(String tmdMachinePhoto) {
		this.tmdMachinePhoto = tmdMachinePhoto;
	}

	@Column(name = "tmd_brief", length = 256)
	public String getTmdBrief() {
		return this.tmdBrief;
	}

	public void setTmdBrief(String tmdBrief) {
		this.tmdBrief = tmdBrief;
	}


	@Column(name = "tmd_machine_id", nullable = false)
	public Long getTmdMachineId() {
		return tmdMachineId;
	}

	public void setTmdMachineId(Long tmdMachineId) {
		this.tmdMachineId = tmdMachineId;
	}

}
