package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbOrderHead generated by hbm2java
 */
@Entity
@Table(name = "tb_order_head")
public class TbOrderHead implements java.io.Serializable {

	private Long tohId;
	private Long tohCompanyId;
	private String tohNumber;//订单编号
	private Integer tohType;//订单类型,1:后台录入  2:客户端生成
	private Long tohCustomerId;//客户id
	private Double tohAmount;//订单金额,可以为空
	private String tohMemo;//订单备注
	private Timestamp tohAddDate;//订单时间
	private Long tohAddPerson;//创建人
	private Integer tohStatus;//状态,1：正常 2：退租 0: 删除
	private String tohContanctPerson;//联系人
	private String tohContactPhone;//联系电话
	private String tohAddress;//联系地址
	private Integer tohProvId;//所属省
	private Integer tohCityId;//所属市
	//private Integer tohCount;//商品总数
	private Long tohAddressId;//收货地址id
	//private Double tohFreight;//运费
	private Timestamp tohPayTime;//支付时间
	private Timestamp tohSendTime;//发货时间
	private Timestamp tohReceiveTime;//收货时间
	
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	@Column(name = "toh_id", unique = true, nullable = false)
	public Long getTohId() {
		return tohId;
	}
	public void setTohId(Long tohId) {
		this.tohId = tohId;
	}
	@Column(name = "toh_number")
	public String getTohNumber() {
		return tohNumber;
	}
	public void setTohNumber(String tohNumber) {
		this.tohNumber = tohNumber;
	}
	@Column(name = "toh_type")
	public Integer getTohType() {
		return tohType;
	}
	public void setTohType(Integer tohType) {
		this.tohType = tohType;
	}
	@Column(name = "toh_customer_id")
	public Long getTohCustomerId() {
		return tohCustomerId;
	}
	public void setTohCustomerId(Long tohCustomerId) {
		this.tohCustomerId = tohCustomerId;
	}
	@Column(name = "toh_amount")
	public Double getTohAmount() {
		return tohAmount;
	}
	public void setTohAmount(Double tohAmount) {
		this.tohAmount = tohAmount;
	}
	
	@Column(name = "tho_memo")
	public String getTohMemo() {
		return tohMemo;
	}
	public void setTohMemo(String tohMemo) {
		this.tohMemo = tohMemo;
	}
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name = "toh_add_date")
	public Timestamp getTohAddDate() {
		return tohAddDate;
	}
	public void setTohAddDate(Timestamp tohAddDate) {
		this.tohAddDate = tohAddDate;
	}
	@Column(name = "toh_add_person")
	public Long getTohAddPerson() {
		return tohAddPerson;
	}
	public void setTohAddPerson(Long tohAddPerson) {
		this.tohAddPerson = tohAddPerson;
	}
	@Column(name = "toh_status")
	public Integer getTohStatus() {
		return tohStatus;
	}
	public void setTohStatus(Integer tohStatus) {
		this.tohStatus = tohStatus;
	}
	@Column(name = "toh_contanct_person")
	public String getTohContanctPerson() {
		return tohContanctPerson;
	}
	public void setTohContanctPerson(String tohContanctPerson) {
		this.tohContanctPerson = tohContanctPerson;
	}
	@Column(name = "toh_contact_phone")
	public String getTohContactPhone() {
		return tohContactPhone;
	}
	public void setTohContactPhone(String tohContactPhone) {
		this.tohContactPhone = tohContactPhone;
	}
	@Column(name = "toh_address")
	public String getTohAddress() {
		return tohAddress;
	}
	public void setTohAddress(String tohAddress) {
		this.tohAddress = tohAddress;
	}
	@Column(name = "toh_prov_id")
	public Integer getTohProvId() {
		return tohProvId;
	}
	public void setTohProvId(Integer tohProvId) {
		this.tohProvId = tohProvId;
	}
	@Column(name = "toh_city_id")
	public Integer getTohCityId() {
		return tohCityId;
	}
	public void setTohCityId(Integer tohCityId) {
		this.tohCityId = tohCityId;
	}
	
	@Column(name = "toh_company_id")
	public Long getTohCompanyId() {
		return tohCompanyId;
	}
	public void setTohCompanyId(Long tohCompanyId) {
		this.tohCompanyId = tohCompanyId;
	}
	
	/*@Column(name = "toh_count")
	public Integer getTohCount() {
		return tohCount;
	}
	public void setTohCount(Integer tohCount) {
		this.tohCount = tohCount;
	}*/
	
	@Column(name = "toh_address_id")
	public Long getTohAddressId() {
		return tohAddressId;
	}
	public void setTohAddressId(Long tohAddressId) {
		this.tohAddressId = tohAddressId;
	}
	
	/*@Column(name = "toh_freight")
	public Double getTohFreight() {
		return tohFreight;
	}
	public void setTohFreight(Double tohFreight) {
		this.tohFreight = tohFreight;
	}*/
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name = "toh_pay_time")
	public Timestamp getTohPayTime() {
		return tohPayTime;
	}
	public void setTohPayTime(Timestamp tohPayTime) {
		this.tohPayTime = tohPayTime;
	}
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name = "toh_send_time")
	public Timestamp getTohSendTime() {
		return tohSendTime;
	}
	public void setTohSendTime(Timestamp tohSendTime) {
		this.tohSendTime = tohSendTime;
	}
	
	@JsonFormat(pattern="yyyy-MM-dd HH:mm:ss",timezone="GMT+8")
	@Column(name = "toh_receive_time")
	public Timestamp getTohReceiveTime() {
		return tohReceiveTime;
	}
	public void setTohReceiveTime(Timestamp tohReceiveTime) {
		this.tohReceiveTime = tohReceiveTime;
	}
	public TbOrderHead(Long tohId, String tohNumber, Integer tohType,
			Long tohCustomerId, Double tohAmount, String tohBuyDate,
			String tohMemo, Timestamp tohAddDate, Long tohAddPerson,
			Integer tohStatus, String tohContanctPerson,
			String tohContactPhone, String tohAddress, Integer tohProvId,
			Integer tohCityId) {
		super();
		this.tohId = tohId;
		this.tohNumber = tohNumber;
		this.tohType = tohType;
		this.tohCustomerId = tohCustomerId;
		this.tohAmount = tohAmount;
		this.tohMemo = tohMemo;
		this.tohAddDate = tohAddDate;
		this.tohAddPerson = tohAddPerson;
		this.tohStatus = tohStatus;
		this.tohContanctPerson = tohContanctPerson;
		this.tohContactPhone = tohContactPhone;
		this.tohAddress = tohAddress;
		this.tohProvId = tohProvId;
		this.tohCityId = tohCityId;
	}
	public TbOrderHead() {
		super();
	}
}
