package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbServiceOrderDetail generated by hbm2java
 */
@Entity
@Table(name = "tb_service_order_detail")
public class TbServiceOrderDetail implements java.io.Serializable {

	private Long tsodId;
	private Long tsodHeadId;
	private Timestamp tsodAllocateDate;
	private Long tsodAllocatePerson;
	private Long tsodWorkerId;
	private Timestamp tsodSureDate;
	private Timestamp tsodStartDate;
	private Timestamp tsodEndDate;
	private Timestamp tsodOkDate;
	private Timestamp tsodAbortDate;
	private String tsodEvaluation;
	private String tsodMemo;
	private Boolean tsodResult;
	private Integer tsodStatus;
	private Timestamp tsodVisitDate;
	private String tsodMaintenanceNumber;
	private String tseName;

	@Transient
	public String getTseName() {
		return tseName;
	}

	public void setTseName(String tseName) {
		this.tseName = tseName;
	}

	public TbServiceOrderDetail() {
	}

	public TbServiceOrderDetail(Long tsodHeadId, Timestamp tsodAllocateDate, Long tsodAllocatePerson,
			Long tsodWorkerId, Integer tsodStatus) {
		this.tsodHeadId = tsodHeadId;
		this.tsodAllocateDate = tsodAllocateDate;
		this.tsodAllocatePerson = tsodAllocatePerson;
		this.tsodWorkerId = tsodWorkerId;
		this.tsodStatus = tsodStatus;
	}

	public TbServiceOrderDetail(Long tsodHeadId, Timestamp tsodAllocateDate, Long tsodAllocatePerson,
			Long tsodWorkerId, Timestamp tsodSureDate, Timestamp tsodStartDate, Timestamp tsodEndDate,
			Timestamp tsodOkDate, Timestamp tsodAbortDate, String tsodEvaluation, String tsodMemo,
			Boolean tsodResult, Integer tsodStatus, Timestamp tsodVisitDate, String tsodMaintenanceNumber) {
		this.tsodHeadId = tsodHeadId;
		this.tsodAllocateDate = tsodAllocateDate;
		this.tsodAllocatePerson = tsodAllocatePerson;
		this.tsodWorkerId = tsodWorkerId;
		this.tsodSureDate = tsodSureDate;
		this.tsodStartDate = tsodStartDate;
		this.tsodEndDate = tsodEndDate;
		this.tsodOkDate = tsodOkDate;
		this.tsodAbortDate = tsodAbortDate;
		this.tsodEvaluation = tsodEvaluation;
		this.tsodMemo = tsodMemo;
		this.tsodResult = tsodResult;
		this.tsodStatus = tsodStatus;
		this.tsodVisitDate = tsodVisitDate;
		this.tsodMaintenanceNumber = tsodMaintenanceNumber;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tsod_id", unique = true, nullable = false)
	public Long getTsodId() {
		return this.tsodId;
	}

	public void setTsodId(Long tsodId) {
		this.tsodId = tsodId;
	}

	@Column(name = "tsod_head_id", nullable = false)
	public Long getTsodHeadId() {
		return this.tsodHeadId;
	}

	public void setTsodHeadId(Long tsodHeadId) {
		this.tsodHeadId = tsodHeadId;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_allocate_date", nullable = false, length = 19)
	public Timestamp getTsodAllocateDate() {
		return this.tsodAllocateDate;
	}

	public void setTsodAllocateDate(Timestamp tsodAllocateDate) {
		this.tsodAllocateDate = tsodAllocateDate;
	}

	@Column(name = "tsod_allocate_person", nullable = false)
	public Long getTsodAllocatePerson() {
		return this.tsodAllocatePerson;
	}

	public void setTsodAllocatePerson(Long tsodAllocatePerson) {
		this.tsodAllocatePerson = tsodAllocatePerson;
	}

	@Column(name = "tsod_worker_id", nullable = false)
	public Long getTsodWorkerId() {
		return this.tsodWorkerId;
	}

	public void setTsodWorkerId(Long tsodWorkerId) {
		this.tsodWorkerId = tsodWorkerId;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_sure_date", length = 19)
	public Timestamp getTsodSureDate() {
		return this.tsodSureDate;
	}

	public void setTsodSureDate(Timestamp tsodSureDate) {
		this.tsodSureDate = tsodSureDate;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_start_date", length = 19)
	public Timestamp getTsodStartDate() {
		return this.tsodStartDate;
	}

	public void setTsodStartDate(Timestamp tsodStartDate) {
		this.tsodStartDate = tsodStartDate;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_end_date", length = 19)
	public Timestamp getTsodEndDate() {
		return this.tsodEndDate;
	}

	public void setTsodEndDate(Timestamp tsodEndDate) {
		this.tsodEndDate = tsodEndDate;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_ok_date", length = 19)
	public Timestamp getTsodOkDate() {
		return this.tsodOkDate;
	}

	public void setTsodOkDate(Timestamp tsodOkDate) {
		this.tsodOkDate = tsodOkDate;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "Tsod_abort_date", length = 19)
	public Timestamp getTsodAbortDate() {
		return this.tsodAbortDate;
	}

	public void setTsodAbortDate(Timestamp tsodAbortDate) {
		this.tsodAbortDate = tsodAbortDate;
	}

	@Column(name = "tsod_evaluation", length = 100)
	public String getTsodEvaluation() {
		return this.tsodEvaluation;
	}

	public void setTsodEvaluation(String tsodEvaluation) {
		this.tsodEvaluation = tsodEvaluation;
	}

	@Column(name = "Tsod_memo", length = 1024)
	public String getTsodMemo() {
		return this.tsodMemo;
	}

	public void setTsodMemo(String tsodMemo) {
		this.tsodMemo = tsodMemo;
	}

	@Column(name = "tsod_result")
	public Boolean getTsodResult() {
		return this.tsodResult;
	}

	public void setTsodResult(Boolean tsodResult) {
		this.tsodResult = tsodResult;
	}

	@Column(name = "tsod_status", nullable = false)
	public Integer getTsodStatus() {
		return this.tsodStatus;
	}

	public void setTsodStatus(Integer tsodStatus) {
		this.tsodStatus = tsodStatus;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsod_visit_date", length = 19)
	public Timestamp getTsodVisitDate() {
		return this.tsodVisitDate;
	}

	public void setTsodVisitDate(Timestamp tsodVisitDate) {
		this.tsodVisitDate = tsodVisitDate;
	}

	@Column(name = "tsod_maintenance_number", length = 254)
	public String getTsodMaintenanceNumber() {
		return this.tsodMaintenanceNumber;
	}

	public void setTsodMaintenanceNumber(String tsodMaintenanceNumber) {
		this.tsodMaintenanceNumber = tsodMaintenanceNumber;
	}

}
