package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import static javax.persistence.GenerationType.IDENTITY;

import java.sql.Timestamp;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;

import com.fasterxml.jackson.annotation.JsonFormat;

/**
 * TbServicePoints generated by hbm2java
 */
@Entity
@Table(name = "tb_service_points")
public class TbServicePoints implements java.io.Serializable {

	private Long tspId;
	private Long tspCompanyId;
	private String tspName;
	private String tspSimpleName;
	private Long tspProvId;
	private Long tspCityId;
	private Long tspCountyId;
	private String tspAddress;
	private String tspPosition;
	private String tspChargePerson;
	private String tspChargePhone;
	private Timestamp tspAddDate;
	private Long tspAddPerson;
	private Integer tspStatus;
	private String tspLoginUser;
	private String tspLoginPass;
	private Long tspType;
	private String twName;
	private String tspPhoto;
	private String pname;
	private String cname;
	private String tspServiceNum;

	public TbServicePoints() {
	}

	public TbServicePoints(String tspName, String tspSimpleName, Integer tspStatus) {
		this.tspName = tspName;
		this.tspSimpleName = tspSimpleName;
		this.tspStatus = tspStatus;
	}

	public TbServicePoints(Long tspCompanyId, String tspName, String tspSimpleName, Long tspProvId, Long tspCityId, String tspAddress,
			String tspPosition, String tspChargePerson, String tspChargePhone, Timestamp tspAddDate, Long tspAddPerson,
			Integer tspStatus, String tspLoginUser, String tspLoginPass, Long tspType, String tspPhoto,String tspServiceNum) {
		this.tspCompanyId = tspCompanyId;
		this.tspName = tspName;
		this.tspSimpleName = tspSimpleName;
		this.tspProvId = tspProvId;
		this.tspCityId = tspCityId;
		this.tspAddress = tspAddress;
		this.tspPosition = tspPosition;
		this.tspChargePerson = tspChargePerson;
		this.tspChargePhone = tspChargePhone;
		this.tspAddDate = tspAddDate;
		this.tspAddPerson = tspAddPerson;
		this.tspStatus = tspStatus;
		this.tspLoginUser = tspLoginUser;
		this.tspLoginPass = tspLoginPass;
		this.tspType = tspType;
		this.tspPhoto = tspPhoto;
		this.tspServiceNum = tspServiceNum;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tsp_id", unique = true, nullable = false)
	public Long getTspId() {
		return this.tspId;
	}

	public void setTspId(Long tspId) {
		this.tspId = tspId;
	}

	@Column(name = "tsp_name", nullable = false, length = 50)
	public String getTspName() {
		return this.tspName;
	}

	public void setTspName(String tspName) {
		this.tspName = tspName;
	}

	@Column(name = "tsp_simple_name", nullable = false, length = 10)
	public String getTspSimpleName() {
		return this.tspSimpleName;
	}

	public void setTspSimpleName(String tspSimpleName) {
		this.tspSimpleName = tspSimpleName;
	}

	@Column(name = "tsp_prov_id")
	public Long getTspProvId() {
		return this.tspProvId;
	}

	public void setTspProvId(Long tspProvId) {
		this.tspProvId = tspProvId;
	}

	@Column(name = "tsp_city_id")
	public Long getTspCityId() {
		return this.tspCityId;
	}

	public void setTspCityId(Long tspCityId) {
		this.tspCityId = tspCityId;
	}

	@Column(name = "tsp_address", length = 200)
	public String getTspAddress() {
		return this.tspAddress;
	}

	public void setTspAddress(String tspAddress) {
		this.tspAddress = tspAddress;
	}

	@Column(name = "tsp_position", length = 100)
	public String getTspPosition() {
		return this.tspPosition;
	}

	public void setTspPosition(String tspPosition) {
		this.tspPosition = tspPosition;
	}

	@Column(name = "tsp_charge_person", length = 10)
	public String getTspChargePerson() {
		return this.tspChargePerson;
	}

	public void setTspChargePerson(String tspChargePerson) {
		this.tspChargePerson = tspChargePerson;
	}

	@Column(name = "tsp_charge_phone", length = 21)
	public String getTspChargePhone() {
		return this.tspChargePhone;
	}

	public void setTspChargePhone(String tspChargePhone) {
		this.tspChargePhone = tspChargePhone;
	}

	@JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss", timezone = "GMT+08:00")
	@Column(name = "tsp_add_date", length = 19)
	public Timestamp getTspAddDate() {
		return this.tspAddDate;
	}

	public void setTspAddDate(Timestamp tspAddDate) {
		this.tspAddDate = tspAddDate;
	}

	@Column(name = "tsp_add_person")
	public Long getTspAddPerson() {
		return this.tspAddPerson;
	}

	public void setTspAddPerson(Long tspAddPerson) {
		this.tspAddPerson = tspAddPerson;
	}

	@Column(name = "tsp_status", nullable = false)
	public Integer getTspStatus() {
		return this.tspStatus;
	}

	public void setTspStatus(Integer tspStatus) {
		this.tspStatus = tspStatus;
	}

	@Column(name = "tsp_login_user", length = 20)
	public String getTspLoginUser() {
		return this.tspLoginUser;
	}

	public void setTspLoginUser(String tspLoginUser) {
		this.tspLoginUser = tspLoginUser;
	}

	@Column(name = "tsp_login_pass", length = 50)
	public String getTspLoginPass() {
		return this.tspLoginPass;
	}

	public void setTspLoginPass(String tspLoginPass) {
		this.tspLoginPass = tspLoginPass;
	}

	@Column(name = "tsp_type")
	public Long getTspType() {
		return this.tspType;
	}

	public void setTspType(Long tspType) {
		this.tspType = tspType;
	}

	@Column(name = "tsp_photo", length = 200)
	public String getTspPhoto() {
		return this.tspPhoto;
	}

	public void setTspPhoto(String tspPhoto) {
		this.tspPhoto = tspPhoto;
	}
	
	@Column(name = "tsp_company_id")
	public Long getTspCompanyId() {
		return tspCompanyId;
	}

	public void setTspCompanyId(Long tspCompanyId) {
		this.tspCompanyId = tspCompanyId;
	}

	@Transient
	public String getPname() {
		return pname;
	}

	public void setPname(String pname) {
		this.pname = pname;
	}

	@Transient
	public String getCname() {
		return cname;
	}

	public void setCname(String cname) {
		this.cname = cname;
	}

	@Transient
	public String getTwName() {
		return twName;
	}

	public void setTwName(String twName) {
		this.twName = twName;
	}

	@Column(name = "tsp_service_num", length = 10)
	public String getTspServiceNum() {
		return tspServiceNum;
	}

	public void setTspServiceNum(String tspServiceNum) {
		this.tspServiceNum = tspServiceNum;
	}

	@Column(name = "tsp_county_id", length = 10)
	public Long getTspCountyId() {
		return tspCountyId;
	}

	public void setTspCountyId(Long tspCountyId) {
		this.tspCountyId = tspCountyId;
	}

	
	
}
