package com.src.api.entity;
// Generated 2015-8-31 15:24:09 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TbVcode generated by hbm2java
 */
@Entity
@Table(name = "tb_vcode")
public class TbVcode implements java.io.Serializable {

	private Long tvId;
	private String tvPhone;
	private String tvCode;
	private Integer tvType;
	private Date tvAddDate;

	public TbVcode() {
	}

	public TbVcode(String tvPhone, String tvCode, Integer tvType, Date tvAddDate) {
		this.tvPhone = tvPhone;
		this.tvCode = tvCode;
		this.tvType = tvType;
		this.tvAddDate = tvAddDate;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "tv_id", unique = true, nullable = false)
	public Long getTvId() {
		return this.tvId;
	}

	public void setTvId(Long tvId) {
		this.tvId = tvId;
	}

	@Column(name = "tv_phone", nullable = false)
	public String getTvPhone() {
		return this.tvPhone;
	}

	public void setTvPhone(String tvPhone) {
		this.tvPhone = tvPhone;
	}

	@Column(name = "tv_code", nullable = false, length = 20)
	public String getTvCode() {
		return this.tvCode;
	}

	public void setTvCode(String tvCode) {
		this.tvCode = tvCode;
	}

	@Column(name = "tv_type", nullable = false)
	public Integer getTvType() {
		return this.tvType;
	}

	public void setTvType(Integer tvType) {
		this.tvType = tvType;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "tv_add_date", nullable = false, length = 19)
	public Date getTvAddDate() {
		return this.tvAddDate;
	}

	public void setTvAddDate(Date tvAddDate) {
		this.tvAddDate = tvAddDate;
	}

}
